"""PDF Security Report generator using reportlab."""
from __future__ import annotations
from datetime import datetime
from io import BytesIO
from reportlab.lib.pagesizes import A4
from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import mm
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, HRFlowable
from reportlab.lib.enums import TA_CENTER, TA_LEFT

DARK_BG = colors.HexColor("#0B1220")
CYAN = colors.HexColor("#22D3EE")
CYAN_LIGHT = colors.HexColor("#A5F3FC")
DANGER = colors.HexColor("#F87171")
WARNING = colors.HexColor("#FACC15")
SUCCESS = colors.HexColor("#34D399")
SLATE_400 = colors.HexColor("#94A3B8")
SLATE_300 = colors.HexColor("#CBD5E1")
SLATE_700 = colors.HexColor("#334155")
WHITE = colors.white


def build_security_report_pdf(
    *,
    actor_email: str,
    time_range: str,
    total_analyses: int,
    high_risk: int,
    suspicious: int,
    safe: int,
    system_status: str,
    top_channel: str,
    channel_breakdown: list[dict],
    top_incidents: list[dict],
    top_indicators: list[dict],
    quality_metrics: list[dict],
    stored_analyses: int,
    stored_reports: int,
    stored_incidents: int,
) -> bytes:
    buffer = BytesIO()
    doc = SimpleDocTemplate(
        buffer,
        pagesize=A4,
        topMargin=20 * mm,
        bottomMargin=20 * mm,
        leftMargin=18 * mm,
        rightMargin=18 * mm,
    )

    styles = getSampleStyleSheet()
    title_style = ParagraphStyle("apg_title", fontSize=22, textColor=CYAN, alignment=TA_CENTER, spaceAfter=2 * mm, fontName="Helvetica-Bold")
    subtitle_style = ParagraphStyle("apg_sub", fontSize=11, textColor=SLATE_300, alignment=TA_CENTER, spaceAfter=1 * mm)
    section_style = ParagraphStyle("apg_section", fontSize=13, textColor=CYAN_LIGHT, spaceBefore=6 * mm, spaceAfter=3 * mm, fontName="Helvetica-Bold")
    body_style = ParagraphStyle("apg_body", fontSize=9, textColor=SLATE_300, spaceAfter=1 * mm, leading=14)
    small_style = ParagraphStyle("apg_small", fontSize=8, textColor=SLATE_400)
    footer_style = ParagraphStyle("apg_footer", fontSize=8, textColor=SLATE_400, alignment=TA_CENTER)

    def table_style_base():
        return TableStyle([
            ("BACKGROUND", (0, 0), (-1, 0), SLATE_700),
            ("TEXTCOLOR", (0, 0), (-1, 0), CYAN_LIGHT),
            ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
            ("FONTSIZE", (0, 0), (-1, -1), 9),
            ("TEXTCOLOR", (0, 1), (-1, -1), SLATE_300),
            ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.HexColor("#101827"), colors.HexColor("#0D1520")]),
            ("GRID", (0, 0), (-1, -1), 0.3, SLATE_700),
            ("TOPPADDING", (0, 0), (-1, -1), 5),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
            ("LEFTPADDING", (0, 0), (-1, -1), 8),
            ("RIGHTPADDING", (0, 0), (-1, -1), 8),
            ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
        ])

    generated_at = datetime.utcnow().strftime("%Y-%m-%d %H:%M UTC")
    total = max(total_analyses, 1)

    story = []

    # ── Cover ──────────────────────────────────────────────────────────────
    story.append(Spacer(1, 10 * mm))
    story.append(Paragraph("APG Admin Console", title_style))
    story.append(Paragraph("Arabic Phishing Guard — Security Operations Report", subtitle_style))
    story.append(HRFlowable(width="100%", thickness=0.5, color=CYAN, spaceAfter=4 * mm))
    story.append(Paragraph(f"Generated: {generated_at}", small_style))
    story.append(Paragraph(f"Period: {time_range.title()}", small_style))
    story.append(Paragraph(f"Generated by: {actor_email}", small_style))
    story.append(Spacer(1, 6 * mm))

    # ── Executive Summary ──────────────────────────────────────────────────
    story.append(Paragraph("1. Executive Summary", section_style))
    safe_pct = round(safe / total * 100)
    susp_pct = round(suspicious / total * 100)
    risk_pct = round(high_risk / total * 100)
    summary_data = [
        ["Metric", "Value"],
        ["Total Analyses", str(total_analyses)],
        ["High Risk", f"{high_risk} ({risk_pct}%)"],
        ["Suspicious", f"{suspicious} ({susp_pct}%)"],
        ["Safe", f"{safe} ({safe_pct}%)"],
        ["System Status", system_status.upper()],
        ["Top Channel", top_channel],
        ["Top Indicator", "OTP Request"],
    ]
    t = Table(summary_data, colWidths=[80 * mm, 90 * mm])
    t.setStyle(table_style_base())
    story.append(t)

    # ── Risk Distribution ──────────────────────────────────────────────────
    story.append(Paragraph("2. Risk Distribution", section_style))
    risk_data = [
        ["Classification", "Count", "Percentage"],
        ["Safe", str(safe), f"{safe_pct}%"],
        ["Suspicious", str(suspicious), f"{susp_pct}%"],
        ["High Risk", str(high_risk), f"{risk_pct}%"],
    ]
    t2 = Table(risk_data, colWidths=[70 * mm, 50 * mm, 50 * mm])
    t2.setStyle(table_style_base())
    # Color rows
    t2.setStyle(TableStyle([
        ("TEXTCOLOR", (0, 1), (-1, 1), SUCCESS),
        ("TEXTCOLOR", (0, 2), (-1, 2), WARNING),
        ("TEXTCOLOR", (0, 3), (-1, 3), DANGER),
    ]))
    story.append(t2)

    # ── Channel Breakdown ──────────────────────────────────────────────────
    story.append(Paragraph("3. Channel Breakdown", section_style))
    chan_total = max(sum(c.get("count", 0) for c in channel_breakdown), 1)
    ch_data = [["Channel", "Count", "Percentage"]]
    for c in channel_breakdown:
        pct = round(c.get("count", 0) / chan_total * 100)
        ch_data.append([c.get("channel", ""), str(c.get("count", 0)), f"{pct}%"])
    t3 = Table(ch_data, colWidths=[70 * mm, 50 * mm, 50 * mm])
    t3.setStyle(table_style_base())
    story.append(t3)

    # ── Top Incidents ──────────────────────────────────────────────────────
    story.append(Paragraph("4. Top Incidents", section_style))
    if top_incidents:
        inc_data = [["Title", "Severity", "Status", "Channel", "Cases", "Action"]]
        for inc in top_incidents[:5]:
            inc_data.append([
                str(inc.get("title", ""))[:40],
                str(inc.get("severity", "")),
                str(inc.get("status", "")),
                str(inc.get("channel", "")),
                str(inc.get("cases_count", "")),
                str(inc.get("recommended_action", ""))[:30],
            ])
        t4 = Table(inc_data, colWidths=[55 * mm, 20 * mm, 22 * mm, 22 * mm, 15 * mm, 36 * mm])
        t4.setStyle(table_style_base())
        story.append(t4)
    else:
        story.append(Paragraph("No incidents recorded.", body_style))

    # ── Top Threat Indicators ──────────────────────────────────────────────
    story.append(Paragraph("5. Top Threat Indicators", section_style))
    ind_data = [["Indicator", "Count"]]
    for ind in top_indicators[:6]:
        ind_data.append([str(ind.get("name", "")), str(ind.get("count", ""))])
    t5 = Table(ind_data, colWidths=[120 * mm, 50 * mm])
    t5.setStyle(table_style_base())
    story.append(t5)

    # ── Detection Quality ──────────────────────────────────────────────────
    story.append(Paragraph("6. Detection Quality", section_style))
    q_data = [["Metric", "Value"]]
    for m in quality_metrics:
        q_data.append([str(m.get("label", "")), f"{m.get('value', '')}%"])
    t6 = Table(q_data, colWidths=[120 * mm, 50 * mm])
    t6.setStyle(table_style_base())
    story.append(t6)

    # ── Stored Data Summary ────────────────────────────────────────────────
    story.append(Paragraph("7. Stored Data Summary", section_style))
    db_data = [
        ["Metric", "Value"],
        ["Stored Analysis Samples", str(stored_analyses)],
        ["Total Reports", str(stored_reports)],
        ["Total Incidents", str(stored_incidents)],
    ]
    t7 = Table(db_data, colWidths=[120 * mm, 50 * mm])
    t7.setStyle(table_style_base())
    story.append(t7)

    # ── Privacy Note ──────────────────────────────────────────────────────
    story.append(Spacer(1, 6 * mm))
    story.append(HRFlowable(width="100%", thickness=0.3, color=SLATE_700, spaceAfter=3 * mm))
    story.append(Paragraph(
        "<b>Privacy Notice:</b> This report contains aggregated security metrics only. "
        "Raw user messages are not included. Sensitive information is masked by default.",
        body_style,
    ))

    # ── Footer ────────────────────────────────────────────────────────────
    story.append(Spacer(1, 4 * mm))
    story.append(Paragraph(f"Generated by APG Admin Console  •  {generated_at}  •  Confidential", footer_style))

    doc.build(story)
    return buffer.getvalue()
